name: "NowSecure - Mobile Security"

on: 
  workflow_call:
    inputs:
        # Used by CodeQL for unique build commands
        build-command: 
          required: true
          type: string
        build-path:
          required: true
          type: string
        nowsecure-group-id:
          required: true
          type: string
        java-version:
          required: false
          type: string
          default: '17'
          
permissions: read-all

jobs:
  # Check for mobile files:
  setup:
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.android-check.outputs.ANDROID }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        
      - name: Check for Android manifest file
        id: android-check
        run: |
          if [ -f "AndroidManifest.xml" ]; then
              echo "ANDROID=true" >> "$GITHUB_OUTPUT"
          else
              echo "Android manifest file not found"
          fi
  # Build and upload an Android application as a build artifact
  build:
    if: ${{ needs.setup.outputs.android != '' }}
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: "microsoft"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build application
        run: ${{ inputs.build-command }}

      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app
          # NEED TO REPLACE HARDCODED UPLOAD PATH
          path: ${{ inputs.build-path }}
          retention-days: 3
          
  # Scan the Android application with NowSecure.
  scan:
    runs-on: ubuntu-latest
    outputs:
      report_id: ${{ steps.upload.outputs.report_id }}
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # NOTE: ripgrep is required for line-of-code identification.
      - name: Install ripgrep
        run: sudo apt-get install -y ripgrep

      - name: Download application
        uses: actions/download-artifact@v3
        with:
          name: app

      - id: upload
        name: NowSecure upload app
        uses: nowsecure/nowsecure-action/upload-app@v3
        with:
          platform_token: ${{ secrets.NS_TOKEN }}
          # NEED TO REPLACE HARDCODED FILE NAME
          app_file: k9mail-debug.apk
          group_id: ${{ inputs.nowsecure-group-id }}

  # Pulls the NowSecure report, converts it to SARIF and uploads it to code scanning.
  upload-results:
    if: ${{ needs.scan.outputs.report_id }}
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: NowSecure download report
        uses: nowsecure/nowsecure-action/convert-sarif@v3
        timeout-minutes: 60
        with:
          report_id: ${{ needs.scan.outputs.report_id }}
          platform_token: ${{ secrets.NS_TOKEN }}
          group_id: ${{ inputs.nowsecure-group-id }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: NowSecure.sarif

      - name: Upload SARIF to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: NowSecure.sarif
          path: ./NowSecure.sarif
