name: Regression Testing

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  scanning:
    uses: callmegreg-demo-org/reusable-security-workflows/.github/workflows/strict-security-scan.yml@main
    secrets: inherit
